// src/utils/pdfExport.js
//
// Generates real PDF files using jsPDF + jspdf-autotable, entirely in the
// browser — no server round-trip. Mirrors the two documents that already
// existed as Word/.docx builders in docxExport.js (which were written but
// never actually wired to a button anywhere) — same content, PDF instead
// of Word, per what was actually asked for.
//
//   buildInfantRecordPdf()  — full record: identity, growth, vaccinations,
//                             lab tests, medications. For the doctor's own
//                             records / printing / referrals.
//
//   buildLabResultsPdf()   — the REVIEWED lab results for one appointment,
//                            meant to be sent directly to the mother once
//                            the doctor has finished reviewing everything.
//
// Both return a File — ready to hand straight to
// directMessageService.sendAttachment({ file, ... }) or download via
// file-saver, without an extra conversion step.

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

const BRAND = '#6D28D9'
const MUTED = '#64748B'
const INK   = '#0F172A'
const TINT  = [237, 233, 254] // #EDE9FE as RGB, what autotable wants

const fmtDate = (d) => d ? new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '—'
const fmtDateTime = (d) => d ? new Date(d).toLocaleString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) : '—'

function letterhead(doc, subtitle) {
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(BRAND)
  doc.text('NurtureX', 105, 18, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(MUTED)
  doc.text(subtitle, 105, 25, { align: 'center' })

  doc.setDrawColor(237, 233, 254)
  doc.setLineWidth(0.5)
  doc.line(14, 30, 196, 30)

  return 40 // y-position to continue writing from
}

function sectionHeading(doc, text, y) {
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(INK)
  doc.text(text, 14, y)
  return y + 7
}

function labelValue(doc, label, value, y) {
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(INK)
  doc.text(`${label}:`, 14, y)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(MUTED)
  doc.text(String(value ?? '—'), 45, y)
  return y + 6
}

function emptyNote(doc, text, y) {
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(10)
  doc.setTextColor(MUTED)
  doc.text(text, 14, y)
  return y + 10
}

function table(doc, head, body, y) {
  autoTable(doc, {
    startY: y,
    head: [head],
    body,
    styles: { fontSize: 9, textColor: INK },
    headStyles: { fillColor: TINT, textColor: [109, 40, 217], fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
  })
  return doc.lastAutoTable.finalY + 10
}

function footer(doc) {
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(8)
    doc.setTextColor(148, 163, 184)
    doc.text(`Generated by NurtureX on ${fmtDateTime(new Date())}`, 14, 289)
    doc.text(`Page ${i} of ${pageCount}`, 196, 289, { align: 'right' })
  }
}

// ── 1. Full infant record ───────────────────────────────────────────────

export function buildInfantRecordPdf({ infant, growth = [], vaccinations = [], labTests = [], medications = [] }) {
  const doc = new jsPDF()
  let y = letterhead(doc, `Infant Medical Record — Generated ${fmtDate(new Date())}`)

  const ageMonths = infant.date_of_birth
    ? Math.floor((Date.now() - new Date(infant.date_of_birth)) / (1000 * 60 * 60 * 24 * 30.44))
    : null

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(INK)
  doc.text(infant.name ?? 'Infant Record', 14, y)
  y += 9

  y = labelValue(doc, 'Date of birth', fmtDate(infant.date_of_birth), y)
  y = labelValue(doc, 'Age', ageMonths != null ? `${ageMonths} months` : '—', y)
  y = labelValue(doc, 'Gender', infant.gender ?? '—', y)
  y = labelValue(doc, 'Blood type', infant.blood_type ?? '—', y)
  y = labelValue(doc, 'Mother', infant.mother?.full_name ?? '—', y)
  y = labelValue(doc, 'Doctor', infant.doctor?.full_name ? `Dr. ${infant.doctor.full_name}` : '—', y)
  if (infant.notes) y = labelValue(doc, 'Notes', infant.notes, y)
  y += 6

  y = sectionHeading(doc, 'Growth History', y)
  y = growth.length === 0
    ? emptyNote(doc, 'No growth measurements recorded.', y)
    : table(doc, ['Date', 'Weight (kg)', 'Height (cm)', 'Head Circ. (cm)'],
        growth.map(g => [fmtDate(g.measured_at), g.weight_kg ?? '—', g.height_cm ?? '—', g.head_circumference ?? '—']), y)

  y = sectionHeading(doc, 'Vaccinations', y)
  y = vaccinations.length === 0
    ? emptyNote(doc, 'No vaccination records.', y)
    : table(doc, ['Vaccine', 'Scheduled', 'Administered', 'Status'],
        vaccinations.map(v => [v.vaccine_name, fmtDate(v.scheduled_date), fmtDate(v.administered_date), v.status]), y)

  y = sectionHeading(doc, 'Lab Tests', y)
  y = labTests.length === 0
    ? emptyNote(doc, 'No lab tests on file.', y)
    : table(doc, ['Test', 'Requested', 'Status', 'Doctor Notes'],
        labTests.map(t => [t.test_name, fmtDate(t.requested_at), t.status, t.doctor_notes ?? '—']), y)

  y = sectionHeading(doc, 'Medications', y)
  y = medications.length === 0
    ? emptyNote(doc, 'No medications on file.', y)
    : table(doc, ['Medication', 'Dosage', 'Frequency', 'Duration'],
        medications.map(m => [m.medication_name, m.dosage ?? '—', m.frequency ?? '—', m.duration ?? '—']), y)

  footer(doc)
  return doc
}

// ── 2. Lab results for one appointment (sent to the mother) ────────────

export function buildLabResultsPdf({ infant, appointment, labTests = [], doctorName }) {
  const reviewed = labTests.filter(t => t.status === 'reviewed')

  const doc = new jsPDF()
  let y = letterhead(doc, 'Lab Results')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(INK)
  doc.text(`Results for ${infant?.name ?? 'your baby'}`, 14, y)
  y += 9

  y = labelValue(doc, 'Visit date', fmtDate(appointment?.scheduled_at), y)
  y = labelValue(doc, 'Reviewed by', doctorName ? `Dr. ${doctorName}` : '—', y)
  y = labelValue(doc, 'Reviewed on', fmtDateTime(new Date()), y)
  y += 8

  reviewed.forEach((t) => {
    if (y > 250) { doc.addPage(); y = 20 }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(INK)
    doc.text(t.test_name, 14, y)
    y += 6
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(MUTED)
    const lines = doc.splitTextToSize(t.doctor_notes || 'No additional notes.', 180)
    doc.text(lines, 14, y)
    y += lines.length * 5 + 8
  })

  if (y > 260) { doc.addPage(); y = 20 }
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(9)
  doc.setTextColor(MUTED)
  doc.text('If you have any questions about these results, message your doctor directly in the app.', 14, y + 4)

  footer(doc)
  return doc
}

// ── Shared: turn a jsPDF document into a downloadable/attachable File ───

export function pdfToFile(doc, filename) {
  const blob = doc.output('blob')
  return new File([blob], filename, { type: 'application/pdf' })
}

export function downloadPdf(doc, filename) {
  doc.save(filename)
}
